# Generated by Django 3.2.18 on 2023-03-24 10:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing_django_framework', '0005_alter_snippet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100)),
        ),
    ]
