# Generated by Django 3.2.18 on 2023-04-01 00:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('not_start', 'Not Start'), ('on_going', 'On Going'), ('completed', 'Completed'), ('expired', 'Expired')], default='Not Start', max_length=100)),
        ),
    ]
