# Generated by Django 3.2.18 on 2023-06-21 15:09

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('popularity', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image_url', django_cryptography.fields.encrypt(models.URLField())),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('popularity', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('date', models.DateField()),
                ('content', django_cryptography.fields.encrypt(models.CharField(max_length=500))),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.wellbeing_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Motion',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.RenameField(
            model_name='model_store',
            old_name='model_name',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='model_store',
            old_name='model_store_url',
            new_name='model_url',
        ),
        migrations.RenameField(
            model_name='model_store',
            old_name='model_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='model_store',
            old_name='model_version',
            new_name='version',
        ),
        migrations.AddField(
            model_name='action',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
