# Generated by Django 3.2.18 on 2023-06-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20230621_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
