# Generated by Django 3.2.18 on 2023-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20230701_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='total_time',
            field=models.DateTimeField(),
        ),
    ]
