# Generated by Django 3.2.18 on 2023-04-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_plan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='workout_label',
        ),
        migrations.AddField(
            model_name='practice',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.workout'),
            preserve_default=False,
        ),
    ]
