# Generated by Django 3.2.18 on 2023-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_usersummary_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersummary',
            name='current_month_time',
            field=models.DateTimeField(default=0),
        ),
    ]
