# Generated by Django 3.2.18 on 2023-06-24 07:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20230624_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='recurring_dates',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
    ]
