# Generated by Django 3.2.18 on 2023-04-01 01:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20230401_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.plan'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='end_time',
            field=django_cryptography.fields.encrypt(models.DateTimeField(default=datetime.datetime(2023, 4, 1, 9, 51, 48, 361645))),
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_time',
            field=django_cryptography.fields.encrypt(models.DateTimeField(default=datetime.datetime(2023, 4, 1, 9, 51, 48, 361645))),
        ),
    ]
