# Generated by Django 3.2.18 on 2023-07-02 13:46

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20230702_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100)),
        ),
    ]
