# Generated by Django 3.2.18 on 2023-04-01 11:16

import datetime
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20230401_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='practice',
            name='end_time',
            field=django_cryptography.fields.encrypt(models.DateTimeField(default=datetime.datetime(2023, 4, 1, 19, 16, 47, 220238))),
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_time',
            field=django_cryptography.fields.encrypt(models.DateTimeField(default=datetime.datetime(2023, 4, 1, 19, 16, 47, 220238))),
        ),
    ]
