# Generated by Django 3.2.18 on 2023-06-16 04:00

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20230401_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', django_cryptography.fields.encrypt(models.JSONField(default=dict))),
                ('event_name', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('motion_description', django_cryptography.fields.encrypt(models.TextField())),
                ('event_motions', django_cryptography.fields.encrypt(models.JSONField(default=dict))),
                ('schedule', django_cryptography.fields.encrypt(models.TextField())),
                ('status', django_cryptography.fields.encrypt(models.CharField(choices=[('not_start', 'Not Start'), ('cancel', 'Canceled'), ('on_going', 'On Going'), ('completed', 'Completed'), ('expired', 'Expired')], default='Not Start', max_length=100))),
                ('created', django_cryptography.fields.encrypt(models.DateTimeField(auto_now_add=True))),
                ('updated', django_cryptography.fields.encrypt(models.DateTimeField(auto_now=True))),
                ('event_start_time', django_cryptography.fields.encrypt(models.DateTimeField())),
                ('event_end_time', django_cryptography.fields.encrypt(models.DateTimeField())),
                ('event_location', django_cryptography.fields.encrypt(models.TextField())),
                ('event_version', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Model_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('model_type', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('model_store_url', django_cryptography.fields.encrypt(models.TextField(default=''))),
                ('created', django_cryptography.fields.encrypt(models.DateTimeField(auto_now_add=True))),
                ('updated', django_cryptography.fields.encrypt(models.DateTimeField(auto_now=True))),
                ('model_version', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Resource_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', django_cryptography.fields.encrypt(models.TextField())),
                ('resource_url', django_cryptography.fields.encrypt(models.TextField())),
                ('resource_type', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('expire_time', django_cryptography.fields.encrypt(models.DateTimeField())),
                ('create_time', django_cryptography.fields.encrypt(models.DateTimeField(auto_now_add=True))),
                ('update_time', django_cryptography.fields.encrypt(models.DateTimeField(auto_now=True))),
                ('resource_version', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', django_cryptography.fields.encrypt(models.JSONField(default=dict))),
                ('ver_url', django_cryptography.fields.encrypt(models.TextField())),
                ('ver_status', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('expire_time', django_cryptography.fields.encrypt(models.DateTimeField())),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wellbeing_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('user_email', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('user_password', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('user_phone', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('create_time', django_cryptography.fields.encrypt(models.DateTimeField(auto_now_add=True))),
                ('update_time', django_cryptography.fields.encrypt(models.DateTimeField(auto_now=True))),
                ('user_status', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('user_type', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
                ('last_login', django_cryptography.fields.encrypt(models.DateTimeField())),
                ('user_group', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=100))),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('user_name', 'user_email')},
            },
        ),
        migrations.RemoveField(
            model_name='practice',
            name='motion',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='workout',
        ),
        migrations.AlterModelOptions(
            name='motion',
            options={'ordering': ['-motion_created']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='motion',
            old_name='created',
            new_name='motion_created',
        ),
        migrations.RenameField(
            model_name='motion',
            old_name='name',
            new_name='motion_name',
        ),
        migrations.RenameField(
            model_name='motion',
            old_name='popularity',
            new_name='motion_popularity',
        ),
        migrations.RenameField(
            model_name='motion',
            old_name='ready',
            new_name='motion_ready',
        ),
        migrations.RenameField(
            model_name='motion',
            old_name='type',
            new_name='motion_type',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='plan',
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_demo',
            field=django_cryptography.fields.encrypt(models.TextField(default='')),
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_description',
            field=django_cryptography.fields.encrypt(models.TextField(default='')),
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_model',
            field=django_cryptography.fields.encrypt(models.JSONField(default=dict)),
        ),
        migrations.AddField(
            model_name='motion',
            name='motion_model_type',
            field=django_cryptography.fields.encrypt(models.TextField(default='')),
        ),
        migrations.AddField(
            model_name='workout',
            name='event',
            field=django_cryptography.fields.encrypt(models.JSONField(default=dict)),
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('not_start', 'Not Start'), ('cancel', 'Canceled'), ('on_going', 'On Going'), ('completed', 'Completed'), ('expired', 'Expired')], default='Not Start', max_length=100)),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=django_cryptography.fields.encrypt(models.JSONField(default=dict)),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories',
        ),
        migrations.AddField(
            model_name='workout',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_time',
            field=django_cryptography.fields.encrypt(models.DateTimeField()),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='score',
        ),
        migrations.AddField(
            model_name='workout',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
