# Generated by Django 3.2.18 on 2023-08-19 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0008_badge_reward_userbadge_userpoints_userreward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreward',
            name='user',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userbadges', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpoints',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userpoints', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreward',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userrewards', to='auth.user'),
            preserve_default=False,
        ),
    ]
