# Generated by Django 3.2.18 on 2023-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_rename_user_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='used_points',
            field=models.IntegerField(default=0),
        ),
    ]
