# Generated by Django 3.2.18 on 2023-09-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_profile_used_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.badge'),
        ),
    ]
