# Generated by Django 3.2.18 on 2023-10-07 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wellbeing_django_framework.exercise.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0015_alter_usersummary_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badge',
            field=models.ForeignKey(default=wellbeing_django_framework.exercise.models.Badge.get_default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise.badge'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('liker', 'likee')},
            },
        ),
    ]
