# Generated by Django 3.2.18 on 2023-10-11 13:01

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_auto_20231007_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=django_cryptography.fields.encrypt(models.TextField(default='front end url')),
        ),
    ]
