# Generated by Django 3.2.18 on 2023-10-15 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0017_schedule_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', django_cryptography.fields.encrypt(models.TextField(default=''))),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('inviter', 'invitee')},
            },
        ),
    ]
