# Generated by Django 3.2.18 on 2023-10-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0018_auto_20231015_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
